no more donwloading source

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -8,27 +8,23 @@ plugin_dir=$(dirname "$(dirname "$current_script_path")")
 # shellcheck source=../lib/utils.bash
 source "${plugin_dir}/lib/utils.bash"
 
-function download_source() {
+function download_version() {
   local version=$1
   local download_path=$2
 
-  local source_url
-  source_url=$(get_source_url "$version")
+  local platform
+  platform=$(get_platform)
 
-  local tmpdir
-  tmpdir=$(get_temp_dir)
-  trap "rm -rf $tmpdir" EXIT
+  local arch
+  arch=$(get_arch)
+
+  local bin_url
+  bin_url=$(get_bin_url "$version" "$platform" "$arch")
 
   (
-    mkdir -p "$download_path"
-
-    echo "Downloading source from $source_url"
-    curl -sSfLo "$tmpdir/archive.zip" "$source_url" || fail "Couldn't download source code from $source_url"
-
-    unzip -q "$tmpdir/archive.zip" -d "$tmpdir"
-
-    mv $tmpdir/grain-grain-v$version/* "$download_path/"
-  ) || (rm -rf "$download_path"; exit 1)
+    echo "Downloading Grain v$version binary from $bin_url"
+    curl -sSfLo "$download_path/grain" "$bin_url" || "Couldn't download the Grain binary from $bin_url"
+  ) || (rm -rf "$download_path"; fail "Failed to donwload Grain v$version")
 }
 
-download_source "$ASDF_INSTALL_VERSION" "$ASDF_DOWNLOAD_PATH"
+download_version "$ASDF_INSTALL_VERSION" "$ASDF_DOWNLOAD_PATH"
diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -10,30 +10,22 @@ source "${plugin_dir}/lib/utils.bash"
 
 function install_version() {
   local version=$1
-  local install_path=$2
+  local download_path=$2
+  local install_path=$3
 
-  local platform
-  platform=$(get_platform)
-
-  local arch
-  arch=$(get_arch)
-
-  local bin_url
-  bin_url=$(get_bin_url "$version" "$platform" "$arch")
+  local bin_path="$install_path/bin/grain"
 
   (
-    set -e
-    mkdir -p "$install_path/bin"
+    mkdir -p "$bin_path"
 
     echo "Installing Grain v$version"
-    curl -sSfLo "$install_path/bin/grain" "$bin_url" || fail "Couldn't download the Grain binary from $bin_url"
-
-    chmod +x "$install_path/bin/grain"
-  ) || (rm -rf "$install_path"; exit 1)
+    cp "$download_path/grain" "$bin_path"
+    chmod +x "$bin_path"
+  ) || (rm -rf "$install_path"; fail "Failed to install Grain v$version")
 }
 
 if [ "$ASDF_INSTALL_TYPE" != "version" ]; then
   fail "asdf-grain currently supports release install only"
 fi
 
-install_version "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
+install_version "$ASDF_INSTALL_VERSION" "$ASDF_DOWNLOAD_PATH" "$ASDF_INSTALL_PATH"
